# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company. Licensed under the MIT license.
# Please, see the LICENSE.md file in project's root for full licensing information.
version: "3"

services:
  test:
    image: pggraph
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["pytest", "-s"]
    depends_on:
      - test_db
    networks:
      - test_db_nw

  test_db:
    image: postgres:12
    command:
      postgres -c max_connections=300
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    networks:
      - test_db_nw

networks:
  test_db_nw:
    driver: bridge
